# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `simplecov-lcov` gem.
# Please instead update this file by running `bin/tapioca gem simplecov-lcov`.

module SimpleCovLcov
end
class SimpleCovLcov::Configuration
  def lcov_file_name; end
  def lcov_file_name=(arg0); end
  def output_directory; end
  def output_directory=(arg0); end
  def report_with_single_file=(arg0); end
  def report_with_single_file?; end
  def single_report_path; end
  def single_report_path=(new_path); end
end
module SimpleCov
end
module SimpleCov::Formatter
end
class SimpleCov::Formatter::LcovFormatter
  def create_output_directory!; end
  def filtered_branches(file); end
  def filtered_lines(file); end
  def format(result); end
  def format_branch(branch, branch_idx); end
  def format_branches(file); end
  def format_file(file); end
  def format_line(line); end
  def format_lines(file); end
  def lcov_results_path; end
  def output_directory; end
  def output_filename(filename); end
  def report_with_single_file?; end
  def self.config; end
  def self.report_with_single_file=(value); end
  def single_report_path; end
  def write_lcov!(file); end
  def write_lcov_to_single_file!(files); end
end