#!/usr/bin/env ruby
# typed: strict

require 'pp'
require_relative 'schema.capnp'

IO::Buffer.for(STDIN.read) do |buffer|
  message = CapnProto::Message.new(buffer)

  root = message.root
  exit if root.nil?

  sp = Schema::CodeGeneratorRequest.new(root, 0)
  pp sp.to_h
end
