#!/usr/bin/env ruby
# typed: strict

require 'pp'
require_relative 'generator/generator'

begin
  message = CapnProto::Message.from_io(STDIN)
  generator = CapnProto::Generator.new(message.root)
  generator.generate
rescue => e
  STDERR.puts("#{e.class}: #{e.message}")
  e.backtrace.to_a.reject { |line| line.include?('/gems/sorbet-runtime-') }.each { |line| STDERR.puts(line) }
end
