#!/usr/bin/env ruby
# typed: strict

require 'pp'
require_relative 'generator/generator'

begin
  puts CapnProto::Generator.generate(STDIN.read)
rescue => e
  STDERR.puts("#{e.class}: #{e.message}")
  e.backtrace.to_a.reject { |line| line.include?('/gems/sorbet-runtime-') }.each { |line| STDERR.puts(line) }
end
