require_relative "runtime/capnproto"
require_relative "runtime/buffer"
require_relative "runtime/list"
require_relative "runtime/message"
require_relative "runtime/reference"
require_relative "runtime/struct"
