name: Ruby

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.1.4'

    steps:
    - uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true

    - name: Run the default task
      run: bundle exec rake

    - name: Coveralls
      uses: coverallsapp/github-action@v2
      with:
        flag-name: ruby-${{ matrix.ruby }}
        parallel: true

  finish:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Coveralls Finished
      uses: coverallsapp/github-action@v2
      with:
        flag-name: ruby-${{ matrix.ruby }}
        parallel-finished: true
